### ISSUE TITLE
Would you like to add this repository to CAP's official documentation

### ISSUE THREAD

**Issue by yang-xiaodong** [difudotnet/CAP.RedisMQ.Extensions#1]
Hello there,

I saw this repository. It can be added to the official CAP document as an extension implemented by the community, so that other people can find it here through the document. If you want, you can submit a PR to modify the docs.

https://github.com/dotnetcore/CAP/blob/master/docs/content/user-guide/zh/storage/general.md#%E7%A4%BE%E5%8C%BA%E6%94%AF%E6%8C%81%E7%9A%84%E8%BF%90%E8%BE%93%E5%99%A8

Thanks

**Comment by difuteam** [comment]
已经提交感谢~
